Repository anjaligupta0621/EasyConnect, pull requests merged in 2022-02, with the labels that each got.

#9 Anjali dev
  package-lock.json
  package.json
  public/index-temp.html
  public/index.html
  public/logo.png
  src/App.js
  src/components/home.component.css
  src/components/home.component.js
  src/components/navbar.component.css
  src/components/navbar.component.js
Labels: enhancement

#10 [Issue #3][Milestone #1] Database connection
  backend/dbCreation.go
  backend/endpoints.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: good first issue

#16 [Issue #11] Design Login Authentication API
  backend/dbCreation.go
  backend/endpoints.go
  backend/main.go
Labels: enhancement

#18 Create Sprint1.md
  Sprint1.md
Labels: documentation, User Story-1, sprint1

#19 Update Sprint1.md
  Sprint1.md
Labels: documentation, User Story-1, sprint1

#23 [Sprint-2][Issue#22]JobSeeker UI
  src/.DS_Store
  src/App.js
  src/components/header.component.js
  src/components/jobseeker.component.css
  src/components/jobseeker.component.js
  src/components/navbar.jobseeker.component.css
  src/components/navbar.jobseeker.component.js
  src/css/bootstrap.css
  src/css/pd_stylesheet.css
  src/index.js
Labels: User Story-1, sprint 2

#27 [Sprint 2][Issue #26] Add Docker Build support
  .dockerignore
  Dockerfile
Labels: setup, sprint 2

#28 [Sprint 2][Issue 25][Remove unwanted changes]
  backend/dbCreation 2.go
  backend/endpoints 2.go
  backend/endpoints.go
Labels: User Story-1, sprint 2

#30 [Sprint2][Issue##29][UI Enhancement]
  Dockerfile
  package-lock.json
  package.json
  public/index.html
  src/components/header.component.js
  src/components/home.component.js
  src/components/login.component.js
  src/components/navbar.component.js
  src/components/signup.component.js
  src/css/login-modal-wizard.css
  src/img/login-bg2.png
Labels: User Story-1, sprint 2

#32 [Sprint-2][Issue#31][CORS Permission]
  backend/endpoints.go
  backend/main.go
Labels: User Story-1, sprint 2

#34 [Sprint 2][Issue 33] Return JSON as respnse
  backend/endpoints.go
Labels: User Story-1, sprint 2

#37 [Sprint2][Issue#36][API call Enhancement]
  src/components/login.component.js
  src/components/navbar.component.js
Labels: Enhancement, sprint 2
