Repository anjaligupta0621/EasyConnect, pull requests merged in 2022-03, with the labels that each got.

#39 [Sprint2][Issue #38][JOb Posting Enahncement]
  public/index.html
  src/.DS_Store
  src/components/header.component.js
  src/components/home.component.js
  src/components/jobDetails.component.css
  src/components/jobDetails.component.js
  src/components/login.component 2.js
  src/components/login.component.js
  src/components/navbar.component.js
  src/components/organizationDetails.component.css
  src/components/organizationDetails.component.js
  src/components/postJob.component.js
  src/components/signup.component 2.js
  src/css/main.css
  src/css/styles.css
  src/img/.DS_Store
Labels: Enhancement, sprint 2

#42 [Sprint 2][Issue 41] Support for Job Database
  backend/endpoints.go
  backend/jobEndpoints.go
Labels: User Story-1, Enhancement, sprint 2

#43 [Sprint 2][Added API to add Job]
  backend/dbCreation.go
  backend/jobEndpoints.go
  backend/main.go
Labels: User Story-1, Enhancement, sprint 2

#44 [Sprint 2][Improved Fetch Job API]
  backend/endpoints.go
  backend/jobEndpoints.go
Labels: User Story-1, Enhancement, sprint 2

#49 [Sprint2][Issue #48][Add Job DashBoard]
  src/.DS_Store
  src/App.js
  src/components/header.component.js
  src/components/home.component.js
  src/components/login.component.js
  src/components/navbar.component.js
  src/components/postJob.component.js
  src/components/postJobDashBoard.component.css
  src/components/postJobDashBoard.component.js
  src/components/signup.component 2.js
  src/img/add-job-btn.png
Labels: User Story-1, sprint 2

#54 Gau dev
  backend/dbCreation 2.go
  backend/dbashHandler 2
  backend/endpoints 2.go
  public/index.html
  src/components/header.component.css
  src/components/home.component.css
  src/components/home.component.js
  src/components/job-css.txt
  src/components/navbar.component.css
  src/css/login-modal-wizard 2.css
  src/css/suppress.css
  src/css/utils.css
  src/img/notification-icons/1 3.svg
  src/img/notification-icons/2 3.svg
  src/img/notification-icons/3 3.svg
  src/img/notification-icons/4 3.svg
  src/img/notification-icons/5 3.svg
  src/img/notification-icons/6 4.svg
  src/img/notification-icons/7 3.svg
  src/img/notification-icons/8 3.svg
  src/img/sc2 3.jpg
  src/img/sc22 3.png
  src/img/search 3.png
  src/img/shade 3.png
  src/img/share-link 3.svg
  src/img/steps-shadow 3.png
  src/img/student 3.svg
  src/img/tabicon1 3.png
  src/img/tabicon2 3.png
  src/img/tabicon3 3.png
  src/img/tabicon4 3.png
  src/img/talk 3.png
  src/img/thankyou-btn 3.png
  src/img/top-drpdn-white 3.png
  src/img/user-1 3.png
  src/img/view-tab-bg 3.png
  src/img/wrong 3.png
Labels: sprint 2

#57 Duplicate file Deletion
  backend/dbCreation 2.go
  backend/dbashHandler 2
  backend/endpoints 2.go
  src/css/bootstrap 2.css
  src/css/bootstrap-responsive 2.css
  src/css/bootstrap-theme 2.css
  src/css/bootstrap-theme.min 2.css
  src/css/bootstrap.min 2.css
  src/css/font-awesome.min 2.css
  src/css/login-modal-wizard 2.css
  src/css/main 2.css
  src/css/main-1 2.css
  src/css/main-1.css
  src/css/menu 2.css
  src/css/menu-1 2.css
  src/css/menu-1.css
  src/css/select-drop 2.css
  src/css/selectFx 2.js
  src/css/styles 2.css
Labels: sprint 2

#58 [Sprint 2][Corrected URLs for Post APIs]
  backend/main.go
Labels: User Story-1, sprint 2

#59 UI cypress testing changes
  cypress/integration/uitesting/login_spec.js
  cypress/integration/uitesting/logout_spec.js
  cypress/integration/uitesting/postjob_spec.js
Labels: User Story-1, sprint 2

#63 [Sprint 2][Code reorganization into packages
  backend/dbashHandler.go
  backend/dbashJobSelection.go
  backend/go.mod
  backend/handler/endpoints.go
  backend/handler/jobEndpoints.go
  backend/initDB/dbCreation.go
  backend/main.go
  backend/models/models.go
  backend/server/server.go
Labels: User Story-1, Enhancement, setup, sprint 2

#64 [Sprint 2][Issue 60][Backend UnitTesting]
  backend/dashboardAPI_test.go
  backend/endpoints_test.go
  backend/go.mod
  backend/go.sum
  backend/jobEndpoints_test.go
  backend/models/models.go
Labels: User Story-1, sprint 2

#65 Detailed Documentation for Sprint2
  sprint2.md
  src/components/login.component.js
Labels: User Story-1, sprint 2

#66 [Sprint 2][Issue 60] Added unit tests for Job APIs
  backend/handler/jobEndpoints.go
  backend/jobEndpoints_test.go
Labels: User Story-1, Enhancement, sprint 2

#70 Final Sprint2.md
  sprint2.md
Labels: documentation, sprint 2

#72 [Sprint 3][Handling duplicate entries]
  backend/handler/endpoints.go
Labels: User Story-2, sprint3

#74 Code Refactor and Enhancement the Existing code. Add the User Candidate Profile.
  cypress/integration/uitesting/logout_spec.js
  src/.DS_Store
  src/components/header.component.js
  src/components/home.component.js
  src/components/jobDetails.component.js
  src/components/jobseeker.component.css
  src/components/jobseeker.component.js
  src/components/navbar.component.js
  src/components/navbar.jobseeker.component.js
  src/css/.DS_Store
  src/css/main1.css
  src/css/menu1.css
  src/img/accordion-minus.gif
  src/img/accordion-plus.gif
Labels: Enhancement

#76 Sprint3[Issue #75] Revamping the Style.
  package-lock.json
  package.json
  public/index.html
  src/components/header.component.js
  src/components/home.component.css
  src/components/home.component.js
  src/components/jobseeker.component.css
  src/components/jobseeker.component.js
  src/css/main.css
  src/css/main1.css
  src/css/menu.css
  src/css/menu1.css
  src/css/styles.css
  src/css/utils.css
  src/img/.DS_Store
  src/img/logo-2-seek.svg
Labels: Enhancement, sprint3, User Story 3

#78 Quick Fix to Display the Jobs
  src/App.js
  src/components/header.component.js
  src/components/jobseeker.component.css
  src/components/jobseeker.component.js
Labels: Enhancement, sprint3, User Story 3

#79 [Sprint 3][Adding API for Applicant's perspective]
  backend/handler/jobEndpoints.go
  backend/server/server.go
Labels: Enhancement, sprint3, User Story 3

#86 [Sprint 3][Issue 25][Designing model for Candidate Profile]
  backend/handler/candidateEndpoints.go
  backend/initDB/dbCreation.go
  backend/models/models.go
  backend/server/server.go
  backend/utils/utils.go
Labels: User Story-2, Enhancement, sprint3, sprint 2, User Story 3

#88 Adding component for the Shortlist Candidates
  src/components/Routes.component.js
  src/components/header.component.js
  src/components/postJob.component.js
  src/components/postJobComponent.css
  src/components/postJobDashBoard.component.css
  src/components/postJobDashBoard.component.js
  src/components/shortlistCandidate.component.css
  src/components/shortlistCandidate.component.js
Labels: sprint3, User Story 3

#91 Login API Updates
  backend/handler/endpoints.go
  backend/server/server.go
Labels: Enhancement

#97 Local Storage and Session handling.
  src/components/Routes.component.js
  src/components/header.component.js
  src/components/home.component.js
  src/components/login.component.js
  src/components/postJobDashBoard.component.js
Labels: Enhancement, sprint3, User Story 3

#98 Quick fixes for some build issues
  src/components/header.component.js
  src/components/home.component.js
  src/components/login.component.js
Labels: Enhancement, sprint3, User Story 3

#99 Refactoring the Code
  src/App.js
  src/components/Routes.component.js
  src/components/header.component.js
  src/components/login.component.js
Labels: Enhancement, sprint3, User Story 3

#101 [Sprint#3]JWT Auth Correction and Response Refractor #100
  backend/endpoints_test.go
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
  backend/initDB/dbCreation.go
  backend/models/models.go
  backend/server/server.go
  backend/utils/utils.go
  package-lock.json
  package.json
  src/components/header.component.js
  src/components/home.component.js
  src/components/login.component.js
  src/css/login-modal-wizard.css
Labels: bug, Enhancement, sprint3, User Story 3

#103 [Sprint#3]JWT Auth Correction and Response Refractor #100 HF
  src/components/header.component.js
  src/components/login.component.js
Labels: bug, sprint3, User Story 3
