Repository anjaligupta0621/EasyConnect, pull requests merged in 2022-04, with the labels that each got.

#108 [Sprint 3][Correcting relationships between tables]
  backend/go.mod
  backend/go.sum
  backend/handler/candidateEndpoints.go
  backend/initDB/dbCreation.go
  backend/models/models.go
Labels: bug, sprint3, User Story 3

#110 [Sprint#3] Candidate API JWT Auth #109
  backend/handler/candidateEndpoints.go
  backend/models/models.go
  backend/utils/utils.go
  src/components/jobSeekerHeader.component.js
  src/components/userLoginModal.component.js
Labels: Enhancement, sprint3, User Story 3

#111 [Sprint 3][Quick Fix]
  backend/handler/candidateEndpoints.go
Labels: bug, sprint3, User Story 3

#112 [Sprint#3] Candidate API JWT Auth #109
  backend/handler/candidateEndpoints.go
Labels: bug, Enhancement, sprint3, User Story 3

#113 [Sprint#3] Candidate API JWT Auth Login/Signup QF
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
Labels: bug

#114 Candidate API JWT Auth QHF Review
  src/components/jobSeekerHeader.component.js
  src/components/userLoginModal.component.js
Labels: bug

#115 Home Screen Logo Fix
  src/components/home.component.js
  src/css/utils.css
Labels: Enhancement, sprint3, User Story 3

#116 Json Encoding Issue for Frontend And Backend
  backend/handler/candidateEndpoints.go
  src/components/userLoginModal.component.js
Labels: bug, sprint3, User Story 3

#118 [Sprint 3][Adding apply job API]
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
  backend/handler/jobEndpoints.go
  backend/models/models.go
  backend/server/server.go
Labels: Enhancement, sprint3, User Story 3

#120 Post Job Cypress Unit test #119
  cypress/integration/uitesting/postjob_spec.js
  src/components/header.component.js
  src/components/home.component.js
  src/components/jobDetails.component.js
  src/components/jobSeekerHeader.component.js
  src/components/organizationDetails.component.js
  src/components/postJobDashBoard.component.js
Labels: sprint3, User Story 3, Test

#121 Cypress testing for the Frontend Components
  cypress/integration/uitesting/applyJob_spec.js
  cypress/integration/uitesting/candidateLogin_spec.js
  cypress/integration/uitesting/candidateSignOut_spec.js
  cypress/integration/uitesting/candidateSignUp_spec.js
  cypress/integration/uitesting/switchRecruiter_spec.js
  src/components/userLoginModal.component.js
Labels: Enhancement, sprint3, User Story 3

#122 [Sprint 3][Unit Tests for Backend]
  backend/candidateEndpoints_test.go
  backend/endpoints_test.go
  backend/jobEndpoints_test.go
Labels: sprint3, User Story 3, Test

#123 Post Job Cypress Unit test #119
  backend/jobEndpoints_test.go
  backend/tests/jobEndpoints_test.go
Labels: sprint3, User Story 3, Test

#124 Quick Fixes for Some parameter Fixing
  cypress/integration/uitesting/applyJob_spec.js
  cypress/integration/uitesting/candidateSignUp_spec.js
  cypress/integration/uitesting/switchRecruiter_spec.js
  src/components/postJobDashBoard.component.js
Labels: Enhancement, sprint3, User Story 3

#127 Display all the Applicant[#Sprint4]
  src/.DS_Store
  src/components/Routes.component.js
  src/components/organizationDetails.component.js
  src/components/shortlistCandidate.component.css
  src/components/shortlistCandidate.component.js
  src/img/candidate-no-img.svg
  src/img/excellent-diamond.svg
  src/img/grammer.png
  src/img/maths.png
  src/img/non-verbal-reasoning.png
  src/img/speaking.png
Labels: setup, sprint 4, User Story 4

#130 [Sprint 4][Adding candidate and job relationship]
  backend/handler/jobEndpoints.go
  backend/models/models.go
Labels: Enhancement, sprint 4, User Story 4

#134 [Sprint 4][API to get applied candidates]
  backend/handler/jobEndpoints.go
  backend/models/models.go
  backend/server/server.go
Labels: Enhancement, sprint 4, User Story 4

#135 [Sprint 4][API to get applicants to specific role]
  backend/handler/jobEndpoints.go
  backend/server/server.go
Labels: Enhancement, sprint 4, User Story 4

#136 Update the Job Details and Shortlisted Candidates
  src/components/jobDetails.component.js
  src/components/jobseeker.component.js
  src/components/postJobDashBoard.component.js
  src/components/shortlistCandidate.component.js
Labels: Enhancement, sprint 4, User Story 4

#138 [Springt 4]#137 Shortlisting Candidate Settings
  RecruiterDetails.db
  backend/.DS_Store
  backend/handler/endpoints.go
  backend/server/server.go
  src/.DS_Store
  src/components/header.component.css
  src/components/header.component.js
  src/components/shortlistCandidate.component.js
  src/css/styles.css
  src/img/.DS_Store
  src/img/.cthink.png.icloud
  src/img/.talk.png.icloud
  src/img/excel-download.svg
  src/img/shortlist-candidate.svg
Labels: Enhancement, sprint 4, User Story 4

#139 [Sprint 4]#Login Error Handling
  src/components/header.component.css
  src/components/login.component.js
  src/css/styles.css
  src/img/cthink.png
  src/img/talk.png
Labels: Enhancement, sprint 4, User Story 4

#143 [Sprint 4] #142 Candidate Profile API
  backend/go.mod
  backend/go.sum
  backend/handler/candidateEndpoints.go
  backend/initDB/dbCreation.go
  backend/models/models.go
  backend/server/server.go
Labels: Enhancement, sprint 4, User Story 4

#145 [Sprint 4]LocalStorage Refractor and Key-Pair setting #144
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
  src/components/header.component.js
  src/components/jobDetails.component.js
  src/components/jobSeekerHeader.component.js
  src/components/jobseeker.component.js
  src/components/login.component.js
  src/components/postJobDashBoard.component.js
  src/components/shortlistCandidate.component.js
  src/components/userLoginModal.component.js
Labels: Enhancement, sprint 4, User Story 4

#147 [Sprint 4] Frontend New Test Cases #146
  cypress/integration/uitesting/frontend_spec.js
  cypress/integration/uitesting/postjob_spec.js
  cypress/videos/uitesting/frontend_spec.js.mp4
  src/components/header.component.js
  src/components/login.component.js
  src/components/userLoginModal.component.js
  src/img/.cthink.png.icloud
  src/img/.talk.png.icloud
  src/img/cthink.png
  src/img/talk.png
Labels: Enhancement, sprint 4, User Story 4

#148 Create LICENSE
  LICENSE
Labels: Enhancement, sprint 4, User Story 4

#149 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Enhancement, sprint 4, User Story 4

#150 [Sprint 4] Candidate Profile Update API #142
  backend/models/models.go
  cypress/.DS_Store
  cypress/videos/.DS_Store
Labels: Enhancement, sprint 4, User Story 4

#154 Filter All Jobs and Applied Jobs
  src/components/jobSeekerHeader.component.css
  src/components/jobseeker.component.js
  src/components/shortlistCandidate.component.js
Labels: Enhancement, sprint 4, User Story 4

#156 [Sprint 4][Unit Tests for backend]
  backend/jobEndpoints_test.go
  backend/models/models.go
  backend/tests/candidate_test.go
Labels: Test, sprint 4, User Story 4

#158 Candidate Profile API #157
  backend/.DS_Store
  backend/handler/jobEndpoints.go
  backend/server/server.go
Labels: Enhancement, sprint 4, User Story 4

#159 [Sprint 4] Candidate Profile API #157
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
  backend/server/server.go
  backend/utils/utils.go
Labels: Enhancement, sprint 4, User Story 4

#161 [Sprint 4] Candidate Profile API #157
  backend/handler/candidateEndpoints.go
  backend/initDB/dbCreation.go
  backend/models/models.go
  cypress/integration/uitesting/frontend_spec.js
  src/components/userLoginModal.component.js
  src/img/.cthink.png.icloud
  src/img/.talk.png.icloud
  src/img/cthink.png
  src/img/talk.png
Labels: Enhancement, sprint 4, User Story 4

#165 [Sprint 4][Unit tests for backend]
  backend/candidateEndpoints_test.go
  backend/endpoints_test.go
  backend/handler/candidateEndpoints.go
  backend/jobEndpoints_test.go
Labels: Test, sprint 4, User Story 4

#166 Candidate Profile API #157
  cypress/integration/uitesting/frontend_spec.js
  cypress/videos/uitesting/frontend_spec.js.mp4
  src/components/jobseeker.component.js
Labels: Enhancement, sprint 4, User Story 4

#167 [Sprint 4][Unit test for getCandidateProfile API]
  backend/candidateEndpoints_test.go
Labels: Test, sprint 4, User Story 4

#169 [Sprint 4] Backend Test case Updates
  backend/candidateEndpoints_test.go
  backend/endpoints_test.go
  backend/handler/candidateEndpoints.go
  backend/handler/endpoints.go
  backend/handler/jobEndpoints.go
  backend/jobEndpoints_test.go
  backend/tests/candidate_test.go
  backend/utils/utils.go
Labels: Test, sprint 4, User Story 4

#172 [Sprint 4] Test QAHF
  backend/candidateEndpoints_test.go
Labels: Test, sprint 4, User Story 4
